import {
    AtSign,
    BadgeCheck,
    Clock,
    Eye,
    GitBranch,
    History,
    Link,
    MessageCircle,
    MessageSquare,
    Radio,
    Reply,
    Send,
    Share2,
    Shuffle,
    Tag,
    User,
    UserCheck,
    UserRoundPlus,
    Users,
} from "lucide-react";
import type { AutomationPlatformCapabilities } from "./types";

export const instagramCapabilities: AutomationPlatformCapabilities = {
    platform: "INSTAGRAM",

    triggers: [
        {
            type: "INSTAGRAM_COMMENT",
            label: "Comment on Post or Reel",
            description: "When someone comments on your post or reel",
            category: "TRIGGER",
            icon: MessageCircle,
            configType: "CONTENT_TARGET",
        },
        {
            type: "INSTAGRAM_STORY_REPLY",
            label: "Story Reply",
            description: "When someone replies to your Instagram story",
            category: "TRIGGER",
            icon: Reply,
        },
        {
            type: "INSTAGRAM_DM",
            label: "Direct Message",
            description: "When someone sends you a direct message",
            category: "TRIGGER",
            icon: Send,
        },
        {
            type: "INSTAGRAM_STORY_SHARE",
            label: "Post or Reel Shared to Story",
            description: "When someone shares your post or reel to their story",
            category: "TRIGGER",
            icon: Share2,
        },
        {
            type: "INSTAGRAM_LIVE_COMMENT",
            label: "Live Comment",
            description: "When someone comments on your Instagram Live",
            category: "TRIGGER",
            icon: Radio,
        },
        {
            type: "INSTAGRAM_REFERRAL",
            label: "Referral Link Click",
            description: "When someone clicks an Instagram referral link",
            category: "TRIGGER",
            icon: Link,
        },
    ],

    conditions: [
        {
            type: "KEYWORD_MATCH",
            label: "Keyword Match",
            description: "Check whether a comment matches keywords",
            category: "CONDITION",
            icon: GitBranch,
        },
        {
            type: "FOLLOWER_STATUS",
            label: "Follower Status",
            description: "Check whether the person follows your account",
            category: "CONDITION",
            icon: UserCheck,
        },
        {
            type: "LAST_INTERACTION",
            label: "Last Interaction",
            description: "Check when the person last interacted with your account",
            category: "CONDITION",
            icon: History,
        },
        {
            type: "LAST_SEEN",
            label: "Last Seen",
            description: "Check when the person was last seen",
            category: "CONDITION",
            icon: Eye,
        },
        {
            type: "FOLLOWER_COUNT",
            label: "Follower Count",
            description: "Check the person's follower count",
            category: "CONDITION",
            icon: Users,
        },
        {
            type: "USERNAME",
            label: "Username",
            description: "Check the person's Instagram username",
            category: "CONDITION",
            icon: AtSign,
        },
        {
            type: "OPTED_IN",
            label: "Opted In",
            description: "Check whether the person has opted in",
            category: "CONDITION",
            icon: UserRoundPlus,
        },
        {
            type: "VERIFIED",
            label: "Verified",
            description: "Check whether the person's Instagram account is verified",
            category: "CONDITION",
            icon: BadgeCheck,
        },
        {
            type: "WE_FOLLOW_USER",
            label: "We Follow Them",
            description: "Check whether your account follows the person",
            category: "CONDITION",
            icon: UserCheck,
        },
        {
            type: "CONTACT_NAME",
            label: "Contact Name",
            description: "Check the person's saved contact name",
            category: "CONDITION",
            icon: User,
        },
        {
            type: "CONTACT_STATUS",
            label: "Contact Status",
            description: "Check whether the contact is new or existing",
            category: "CONDITION",
            icon: UserRoundPlus,
        },
        {
            type: "CONTACT_TAG",
            label: "Contact Tag",
            description: "Check whether the contact has a specific tag",
            category: "CONDITION",
            icon: Tag,
        },
    ],

    actions: [
        {
            type: "SEND_DM",
            label: "Send DM",
            description: "Send a private Instagram message",
            category: "ACTION",
            icon: MessageCircle,
        },
        {
            type: "REPLY_COMMENT",
            label: "Reply to Comment",
            description: "Reply publicly to an Instagram comment",
            category: "ACTION",
            icon: MessageSquare,
        },
    ],

    flow: [
        {
            type: "WAIT",
            label: "Wait",
            description: "Wait before continuing the workflow",
            category: "FLOW",
            icon: Clock,
        },
        {
            type: "RANDOMIZER",
            label: "Randomizer",
            description: "Randomly choose a path in the workflow",
            category: "FLOW",
            icon: Shuffle,
        },
    ],
};